# Generated by Django 4.0.6 on 2022-07-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('aprovado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ponto Turistico',
                'verbose_name_plural': 'Pontos Turisticos',
            },
        ),
    ]
