# Generated by Django 4.0.6 on 2022-07-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
