# Generated by Django 4.0.6 on 2022-07-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
        ('core', '0006_pontoturistico_localizacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'ordering': ('-id',), 'verbose_name': 'Ponto Turistico', 'verbose_name_plural': 'Pontos Turisticos'},
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localizacao.localizacao'),
        ),
    ]
