# Generated by Django 4.0.6 on 2022-07-14 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localizacao',
            options={'ordering': ('id',), 'verbose_name': 'Localização', 'verbose_name_plural': 'Localizações'},
        ),
    ]
